version: '3'
services:
  workspace:
    build: ./workspace
    # ports:
    #   - "8000:8000" php artisan serve
    working_dir: /var/www/mystery_logger
    env_file: 
      - .env
    volumes:
      - ./src:/var/www/mystery_logger:cached
      - ./log/nginx:/var/log/nginx:delegated
      - ./log/php-fpm:/var/log/php-fpm:delegated
    tty: true

  nginx:
    image: nginx:1.19-alpine
    ports: 
      - "8080:80"
      - "1443:443"
    working_dir: /var/www/mystery_logger
    env_file:
      - .env
    volumes:
      - ./src:/var/www/mystery_logger:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./nginx/ssl:/etc/nginx/ssl:delegated
      - ./log/nginx:/var/log/nginx:delegated
      - ./php-fpm/sock:/var/run/php-fpm:delegated

  php-fpm:
    build: ./php-fpm
    # ports:
    #   - "9000:9000" # xdebug
    working_dir: /var/www/mystery_logger
    env_file: 
      - .env
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:delegated
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:delegated
      - ./php-fpm/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf:delegated
      - ./src:/var/www/mystery_logger:cached
      - ./log/php-fpm:/var/log:delegated
      - ./php-fpm/sock/:/var/run/php-fpm/:delegated

  pgsql:
    image: postgres:12.3-alpine
    env_file: 
      - .env
    volumes:
      - ./pgsql/data/:/var/lib/postgresql/data/

  redis:
    image: redis:6.0-alpine
    env_file: 
      - .env
      
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    env_file: 
      - .env

  blackfire:
    image: blackfire/blackfire
    ports:
      - "8707"
    env_file: 
      - .env
  #  docker-compose exec blackfire blackfire curl --header 'X-NAZOLOG-TOKEN: fkkaASjsGelGmmrRtcaGytkEwlLLBcCDioeSA' --insecure 'https://0.0.0.0:1443/v1/products' でprofile

  testing-pgsql:
    image: postgres:12.3-alpine
    env_file: 
      - .env
