<?php

use Illuminate\Database\Seeder;

class OrganizersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('organizers')->insert([
            [
                'service_name' => 'リアル脱出ゲーム',
                'kana_service_name' => 'りあるだっしゅつげーむ',
                'company_name' => '株式会社SCRAP',
                'kana_company_name' => 'すくらっぷ',
                'website' => 'https://realdgame.jp/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '151-0051',
                'addr_prefecture' => '東京都',
                'addr_city' => '渋谷区',
                'addr_block' => '千駄ヶ谷5-20-4',
                'addr_building' => '',
                'tel' => '03-5341-4570',
                'mail' => '',
            ],
            [
                'service_name' => '絶対空間 リアル密室脱出ゲーム',
                'kana_service_name' => 'ぜったいくうかん りあるみっしつだっしゅつげーむ',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'http://www.absolute-space.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '171-0022',
                'addr_prefecture' => '東京都',
                'addr_city' => '豊島区',
                'addr_block' => '南池袋3-18-30',
                'addr_building' => 'ファースト日野ビル 4F',
                'tel' => '03-5944-8840',
                'mail' => 'absolute.space.jp@gmail.com',
            ],
            [
                'service_name' => '謎ハウス リアル謎解き脱出ゲーム',
                'kana_service_name' => 'なぞはうす りあるなぞときだっしゅつげーむ',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'http://www.nazohouse.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '',
                'addr_prefecture' => '',
                'addr_city' => '',
                'addr_block' => '',
                'addr_building' => '',
                'tel' => '',
                'mail' => '',
            ],
            [
                'service_name' => 'NoEscape リアル体験脱出ゲーム',
                'kana_service_name' => 'のーえすけーぷ りあるたいけんだっしゅつげーむ',
                'company_name' => '株式会社ライズエンターテインメント',
                'kana_company_name' => 'らいずえんたーていんめんと',
                'website' => 'https://rise-ent.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '151-0053',
                'addr_prefecture' => '東京都',
                'addr_city' => '渋谷区',
                'addr_block' => '代々木3-46-16',
                'addr_building' => '小野木ビル 5F',
                'tel' => '',
                'mail' => '',
            ],
            [
                'service_name' => '超密室 リアル体験型脱出ゲーム',
                'kana_service_name' => 'ちょうみっしつ りあるたいけんがただっしゅつげーむ',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'http://super-escape.co.jp/wp/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '160-0021',
                'addr_prefecture' => '東京都',
                'addr_city' => '新宿区',
                'addr_block' => '歌舞伎町2-14-12',
                'addr_building' => '光凛ビル B2F',
                'tel' => '03-6380-2240',
                'mail' => 'super_escape626@yahoo.co.jp',
            ],
            [
                'service_name' => '謎キャッスル 体験型謎解き脱出ゲーム',
                'kana_service_name' => 'なぞきゃっする たいけんがたなぞときだっしゅつげーむ',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'https://www.nazocastle.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '179-0081',
                'addr_prefecture' => '東京都',
                'addr_city' => '練馬区',
                'addr_block' => '北町2-17-15',
                'addr_building' => '謎キャッスル',
                'tel' => '03-6281-0850',
                'mail' => '',
            ],
            [
                'service_name' => 'REBUILD -再構築-',
                'kana_service_name' => 'りびるど さいこうちく',
                'company_name' => '株式会社TERRA NOVA',
                'kana_company_name' => 'てらのゔぁ',
                'website' => 'https://rebuild.games/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '101-0061',
                'addr_prefecture' => '東京都',
                'addr_city' => '千代田区',
                'addr_block' => '神田三崎町3-7-12',
                'addr_building' => '清話会ビル 3F',
                'tel' => '',
                'mail' => '',
            ],
            [
                'service_name' => 'サニーサニーピクニック',
                'kana_service_name' => 'さにーさにーぴくにっく',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'https://picnic482.wixsite.com/sunnysunnypicnic',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '103-0022',
                'addr_prefecture' => '東京都',
                'addr_city' => '中央区',
                'addr_block' => '日本橋室町１-12-5',
                'addr_building' => '',
                'tel' => '​03-6873-5772',
                'mail' => 'picnic482@gmail.com',
            ],
            [
                'service_name' => '脱出ゲーム なぞばこ',
                'kana_service_name' => 'だっしゅつげーむ なぞばこ',
                'company_name' => 'インバイトジャパン株式会社',
                'kana_company_name' => 'いんばいとじゃぱん',
                'website' => 'https://www.invitejapan.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '110-0014',
                'addr_prefecture' => '東京都',
                'addr_city' => '台東区',
                'addr_block' => '北上野2-22-7',
                'addr_building' => 'エステ北上野101',
                'tel' => '050-5585-3663',
                'mail' => 'tokyo@invitejapan.com',
            ],
            [
                'service_name' => 'inspyre',
                'kana_service_name' => 'いんすぱいや',
                'company_name' => '株式会社ヒューマックスエンタテインメント',
                'kana_company_name' => 'ひゅーまっくすえんたていんめんと',
                'website' => 'http://hmx-entame.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '163-1422',
                'addr_prefecture' => '東京都',
                'addr_city' => '新宿区',
                'addr_block' => '西新宿3-20-2',
                'addr_building' => '東京オペラシティタワー 32F',
                'tel' => '03-3379-8026',
                'mail' => '',
            ],
            [
                'service_name' => 'なぞともカフェ',
                'kana_service_name' => 'なぞともかふぇ',
                'company_name' => '株式会社バンダイナムコアミューズメント',
                'kana_company_name' => 'ばんだいなむこあみゅーずめんと',
                'website' => 'https://bandainamco-am.co.jp/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '108-8310',
                'addr_prefecture' => '東京都',
                'addr_city' => '港区',
                'addr_block' => '芝浦',
                'addr_building' => '3-1-35',
                'tel' => '',
                'mail' => '',
            ],
            [
                'service_name' => 'Puzzle Room Tokyo',
                'kana_service_name' => 'ぱずるるーむとうきょう',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => '',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '104-0045',
                'addr_prefecture' => '東京都',
                'addr_city' => '中央区',
                'addr_block' => '築地6-27-5',
                'addr_building' => '',
                'tel' => '',
                'mail' => '',
            ],
            [
                'service_name' => 'AR謎解きゲーム',
                'kana_service_name' => 'えーあーる なぞときげーむ',
                'company_name' => 'プレティア・テクノロジーズ株式会社',
                'kana_company_name' => 'ぷれてぃあ・てくのろじーず',
                'website' => 'https://pretiaar.com/corporate/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '141-0033',
                'addr_prefecture' => '東京都',
                'addr_city' => '品川区',
                'addr_block' => '西品川1-1-1',
                'addr_building' => '住友不動産大崎ガーデンタワー 9F TUNNEL TOKYO',
                'tel' => '03-6712-5900',
                'mail' => '',
            ],
            [
                'service_name' => 'NAZOTOWN',
                'kana_service_name' => 'なぞたうん',
                'company_name' => 'DAS株式会社',
                'kana_company_name' => 'でぃーえーえす',
                'website' => 'https://www.d-a-s.jp/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '107-0061',
                'addr_prefecture' => '東京都',
                'addr_city' => '港区',
                'addr_block' => '北青山2-10-17',
                'addr_building' => '202',
                'tel' => '045-319-4533',
                'mail' => '',
            ],
            [
                'service_name' => '忍者屋敷シュリケン',
                'kana_service_name' => 'にんじゃやしき しゅりけん',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => '',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '168-0062',
                'addr_prefecture' => '東京都',
                'addr_city' => '杉並区',
                'addr_block' => '方南2-23-22',
                'addr_building' => '方南ファミリーコーポ共同ビル 3F',
                'tel' => '03-6454-6786',
                'mail' => 'shurikensanno@gmail.com',
            ],
            [
                'service_name' => '東京密室',
                'kana_service_name' => 'とうきょうみっしつ',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'http://www.tk-mysteryroom.com/c.html#/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '101-0021',
                'addr_prefecture' => '東京都',
                'addr_city' => '千代田区',
                'addr_block' => '外神田2-10-8',
                'addr_building' => '富士ビル 2F',
                'tel' => '03-6206-8366',
                'mail' => 'tmr2020akb@gmail.com',
            ],
            [
                'service_name' => 'Q Lab?',
                'kana_service_name' => 'くわとろらぼ',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'https://www.qlab.tokyo/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '125-0061',
                'addr_prefecture' => '東京都',
                'addr_city' => '葛飾区',
                'addr_block' => '亀有3-20-2',
                'addr_building' => '6F',
                'tel' => '070-8443-2922',
                'mail' => '',
            ],
            [
                'service_name' => 'code name: WIZARD',
                'kana_service_name' => 'こーどねーむ うぃざーど',
                'company_name' => '株式会社カクシン',
                'kana_company_name' => 'かくしん',
                'website' => 'https://ajara.kakus.in/wizard/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '107-0062',
                'addr_prefecture' => '東京都',
                'addr_city' => '港区',
                'addr_block' => '南青山4-13-9',
                'addr_building' => 'クレセントヒルズ 1F',
                'tel' => '03-5544-8634',
                'mail' => '',
            ],
            [
                'service_name' => 'XEOXY',
                'kana_service_name' => 'ぜおくしー',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'https://www.xeoxy.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '',
                'addr_prefecture' => '東京都',
                'addr_city' => '新宿区',
                'addr_block' => '西新宿6-26-9',
                'addr_building' => '3F',
                'tel' => '03-6279-0042',
                'mail' => '',
            ],
            [
                'service_name' => 'LUNA HALA',
                'kana_service_name' => 'るなはら',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => 'http://lunahala.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '104-0045',
                'addr_prefecture' => '東京都',
                'addr_city' => '中央区',
                'addr_block' => '築地3-17-10',
                'addr_building' => '',
                'tel' => '070-3336-7116',
                'mail' => '',
            ],
            [
                'service_name' => 'タンブルウィード',
                'kana_service_name' => 'たんぶるうぃーど',
                'company_name' => '株式会社グリーンダイス',
                'kana_company_name' => 'ぐりーんだいす',
                'website' => 'https://greendice.co.jp/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '182-0002',
                'addr_prefecture' => '東京都',
                'addr_city' => '調布市',
                'addr_block' => '仙川町2-11-1',
                'addr_building' => '101',
                'tel' => '',
                'mail' => '',
            ],
            [
                'service_name' => 'NAZO X NAZO劇団',
                'kana_service_name' => 'なぞなぞげきだん',
                'company_name' => '株式会社ハレガケ',
                'kana_company_name' => 'はれがけ',
                'website' => 'https://haregake.com/',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '171-0033',
                'addr_prefecture' => '東京都',
                'addr_city' => '豊島区',
                'addr_block' => '高田3-21-2',
                'addr_building' => 'ユニハイト東京ビル 4F',
                'tel' => '03-6912-7596',
                'mail' => '',
            ],
            [
                'service_name' => 'よだかのレコード',
                'kana_service_name' => 'よだかのれこーど',
                'company_name' => '株式会社stamps',
                'kana_company_name' => 'すたんぷす',
                'website' => 'https://yodaka.info//',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '169-0074',
                'addr_prefecture' => '東京都',
                'addr_city' => '新宿区',
                'addr_block' => '北新宿2-2-26',
                'addr_building' => 'K2',
                'tel' => '03-5337-8650',
                'mail' => '',
            ],
            [
                'service_name' => 'その他',
                'kana_service_name' => 'そのた',
                'company_name' => '',
                'kana_company_name' => '',
                'website' => '',
                'image_name' => '/storage/organizer_img/noimage.png',
                'zipcode' => '',
                'addr_prefecture' => '',
                'addr_city' => '',
                'addr_block' => '',
                'addr_building' => '',
                'tel' => '',
                'mail' => '',
            ],
        ]);
    }
}
